# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function updates the block-specific parameters.
#' 
#' @param betar a vector containing the current values for the block-specific beta parameters
#' @param etar a vector containing the current values for the block-specific eta parameters
#' @param xr a matrix containing the block-specific design matrix
#' @param yr a matrix containing the block-specific outcome vector
#' @param dat a matrix containing the block-specific matrix inverse of t(xr)%*%xr + I
#' @param ur a vector containing the current values for the block-specific u variables
#' @param beta a vector containing the current values for the global beta parameters
#' @param rho a numeric scalar 
#' @param alpha a numeric scalar
#' @param tau a numeric scalar
#' @param n an integer giving the overall sample size for the full data
#' @param ni an integer giving the block-specific sample size
#' @export
ParamUpdates <- function(betar, etar, xr, yr, dat, ur, rr, beta, rho, alpha, tau, n, ni) {
    .Call('_QRADMM_ParamUpdates', PACKAGE = 'QRADMM', betar, etar, xr, yr, dat, ur, rr, beta, rho, alpha, tau, n, ni)
}

QRADMMCPP <- function(x, y, tau, rho, lambda, iter, intercept, penalty, a, lambda1, lambda2) {
    .Call('_QRADMM_QRADMMCPP', PACKAGE = 'QRADMM', x, y, tau, rho, lambda, iter, intercept, penalty, a, lambda1, lambda2)
}

#' @export
matInv <- function(x) {
    .Call('_QRADMM_matInv', PACKAGE = 'QRADMM', x)
}

shrinkcpp1 <- function(u, v) {
    .Call('_QRADMM_shrinkcpp1', PACKAGE = 'QRADMM', u, v)
}

QRADM <- function(xr, yr, ta, rhor, lambdar, iter, intercept, M, penalty, a) {
    .Call('_QRADMM_QRADM', PACKAGE = 'QRADMM', xr, yr, ta, rhor, lambdar, iter, intercept, M, penalty, a)
}

